version: '3'

services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: db
    environment:
      POSTGRES_USER: u
      POSTGRES_PASSWORD: p
      POSTGRES_DB: chat
    expose:
      - 5432
    ports:
      - '5431:5432'
    volumes:
      - db-volumes:/var/lib/postgresql/data

volumes:
  db-volumes: