ktor:
    application:
        modules:
            - chat.com.example.ApplicationKt.module
    deployment:
        port: 8080

db:
    url: "jdbc:postgresql://localhost:5431/chat"
    user: "u"
    pass: "p"
    driver: "org.postgresql.Driver"
    pool: 2

jwt:
    secret: "secret"
    issuer: "http://localhost/"
    audience: "test"
    realm: "chat.com.example"
    expired: 3600000